Test Event Name
test

Response
{
  "errorMessage": "list index out of range",
  "errorType": "IndexError",
  "requestId": "486a0a57-642f-4893-990f-047e0301cc29",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 42, in lambda_handler\n    folder_name = email_id.split('-')[2].rstrip('/') + '/'\n"
  ]
}

Function Logs
START RequestId: 486a0a57-642f-4893-990f-047e0301cc29 Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] IndexError: list index out of range
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 42, in lambda_handler
    folder_name = email_id.split('-')[2].rstrip('/') + '/'END RequestId: 486a0a57-642f-4893-990f-047e0301cc29
REPORT RequestId: 486a0a57-642f-4893-990f-047e0301cc29	Duration: 3330.42 ms	Billed Duration: 3331 ms	Memory Size: 128 MB	Max Memory Used: 84 MB	Init Duration: 360.67 ms

Request ID
486a0a57-642f-4893-990f-047e0301cc29
